
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fspmpdmcsllwwzybpfok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzcG1wZG1jc2xsd3d6eWJwZm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDI3NTgsImV4cCI6MjA1OTc3ODc1OH0.yva0buC0Ab6cccPaN6IaVBXfPSdYBZ7OsQuDeykypSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
